# Generated by Django 5.2.7 on 2025-10-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userdetails',
            name='csvapp_user_email_410efa_idx',
        ),
    ]
